#!/bin/sh

subject="Brute force warning"
admin=$(/bin/cat /root/etc/admin-mail)

list=$(/root/bin/fw-locked-users)

if [ "$list" = "" ]
then
    exit
fi

/usr/bin/mail -s "$subject" "$admin" <<EOF
The following accounts were temporarily disabled:
$list
EOF
