#!/bin/sh

subject="Inactive users report"
admin=admin@feministwiki.org

list=$(/root/bin/fw-inactive-users)

if [ "$list" != "" ]
then
    printf '%s\n' "$list" | /usr/bin/mail -s "$subject" "$admin"
fi
