ExpiresActive on
ExpiresDefault                       "access plus 10 minutes"
ExpiresByType text/css               "access plus 1 month"
ExpiresByType text/javascript        "access plus 1 month"
ExpiresByType application/javascript "access plus 1 month"
ExpiresByType application/font-woff  "access plus 1 year"
ExpiresByType font/woff              "access plus 1 year"
ExpiresByType font/woff2             "access plus 1 year"
ExpiresByType image/*                "access plus 1 year"
